### PR TITLE
FIxing modeller bug for WT case

### PR DESCRIPTION
**Pull request by steven-albanese**
Modeller was throwing an error when given `WT` in the yaml pipeline. 

* fixing the way this is being handled 
* Adding a test for the WT case

### CODE REVIEW

**Comment by steven-albanese** [comment]
Tests are passing, but I'm not sure if I've got the test for the WT case correct

**Comment by andrrizzi** [comment]
Whops! Sorry, it looks like the test I suggested fails because when using `WT` with modeller it doesn't save the pdb file. If that's expected, feel free to substitute
```python
setup_molecule_output_check(exp_builder._db, mol_id, output_path)
os.remove(output_path)  # Remove file for next check.
```
with
```python
exp_builder._db._setup_molecules(mol_id)
assert not os.path.exists(output_path)
```
Can you also update the release history (docs/whatsnew.rst) before merging?

**Comment by steven-albanese** [comment]
Hmm weirdly, it looks like it's actually the second `setupt_molecule_output_check` that is failing: https://github.com/choderalab/yank/blob/bd9a4932d9c704dfa914b32f2373a6c8af82f69b/Yank/tests/test_experiment.py#L1356

Do I need to reinitialize the `ExperimentBuilder` object in between the wild type and mutant case?

**Comment by andrrizzi** [comment]
Hmm. I don't think you should! Can you check what `exp_builder._db.is_molecule_setup(mol_id)` returns after the call to `os.remove(output_path)`?

**Comment by andrrizzi** [comment]
Tests finally pass! Should I merge this and go ahead with a bugfix release?

**Comment by steven-albanese** [comment]
Yep!

**Pull request merged**
