### PR TITLE
Tweaks to YAML interface

### PR DESCRIPTION
**Pull request by andrrizzi**

### CODE REVIEW

**Comment by andrrizzi** [comment]
This fixes #331, implements #334, renames the camelCase options into underscore_case, and fix the paths in the YAML file generated for each combination.

**Comment by jchodera** [comment]
This looks great!  I'm not sure if the automatic underscore-to-OpenMM-CamelCase conversion is going to drive us insane or not, but for now, I'm willing to give it a go!

**Comment by andrrizzi** [comment]
Yeah, I figured it could become confusing so I used the function that convert from camel case to underscore only locally when calling ``createSystem()``. Everything is stored and handled as underscore. Values of openmm options are still in camel case, so for example:
```yaml
solvent:
  vacuum:
    nonbonded_method: NoCutoff
```

**Comment by jchodera** [comment]
> Values of openmm options are still in camel case

Sounds good!

**Comment by andrrizzi** [comment]
Merging then.

**Pull request merged**
