### PR TITLE
Setup all systems before running Yank

### LINKED ISSUE #392: Have combinatorial experiment setup actually set up all systems before running any
This might be more convenient for most users.

### PR DESCRIPTION
**Pull request by andrrizzi**
Fix #392. Waiting for tests to pass.

### CODE REVIEW

**Comment by andrrizzi** [comment]
Ready to be merged!

**Comment by andrrizzi** [comment]
I'm about to commit also automatic detection of MPI execution.

**Comment by jchodera** [comment]
Looks good!  

Do we still want to allow the `mpi:` YAML option in case someone wants to force behavior on or off, or is this just more potential for trouble than its worth?

**Comment by andrrizzi** [comment]
I removed it, but I can add it back. Technically the way to force it is to run yank with `mpirun`. Those environment variables get set for each process only when you run your script with MPI, otherwise those variables are not set.

**Comment by jchodera** [comment]
OK, sounds good to me!

**Comment by andrrizzi** [comment]
Great! I've tested it on the cluster and it seems to work well. Merging.

**Pull request merged**
