### PR TITLE
Fix issue with fully interacting state in analysis

### PR DESCRIPTION
**Pull request by Lnaden**
Fix array size recasting and deconvolution of the fully interacting state.

### CODE REVIEW

**Comment by jchodera** [comment]
Can we print out some more information about which state is fully
interacting and fix the numbering in the other states so they match the
actual alchemical state definitions? We still use that matrix to optimize
spacing of alchemical states right now.

**Comment by Lnaden** [comment]
Right now only `analyze` re-orders the states, and only in that function. Is there something post-analyze which uses the output `u_kln` from the analyze file?

**Comment by jchodera** [comment]
I thought there were some matrices that get printed out, but I think we don't number the `Deltaf_ij` matrix anymore, so maybe this isn't a real concern.

**Comment by Lnaden** [comment]
Only the stochastic tests (fixed in another PR) failed. @andrrizzi if this looks good to you, merge it so we can overhaul the analyze script in general.

**Pull request merged**
