### PR TITLE
Add Python 3.9 and 3.10 to CI matrix

### PR DESCRIPTION
**Pull request by mattwthompson**
This won't work at first because of at least one API break in `collections` but what I detect downstream is almost surely more than what the actual test suite will find.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@mattwthompson see https://github.com/conda-forge/yank-feedstock/pull/4

**Comment by mikemhenry** [comment]
Oh and https://github.com/choderalab/yank/pull/1286

So yah need to make some changes :smile: I had forgotten that you made this PR ages ago!

**Comment by mattwthompson** [comment]
Heh, 2 days isn't quite ages - but happy to see you move forward on this, I think it's one of my last upstreams to get on 310!

**Comment by mikemhenry** [comment]
> Heh, 2 days isn't quite ages - but happy to see you move forward on this, I think it's one of my last upstreams to get on 310!

You are right! I was thinking this was from a totally different thing!

**Pull request closed without merging**
