### PR TITLE
Add support for temperatures at intermediate states in YAML.

### LINKED ISSUE #668: Intermediate states at increased temperature
Can you post suggestions on how to run an intermediate state at a different temperature than the end states?

### PR DESCRIPTION
**Pull request by andrrizzi**
Fix #668 .

This was so easy. Should be ready for review if tests pass.

### CODE REVIEW

**Comment by Lnaden** [comment]
Can you add documentation to this in the docs?

**Comment by andrrizzi** [comment]
> Can you add documentation to this in the docs?

I plan to do it soon in a separate PR. There are several changes I already need to make to the docs.

**Comment by jchodera** [comment]
This looks great!

My only question is how much error checking we might want to add to make sure users don't have mismatched temperatures. In principle, the `lambda=0` state can have an arbitrarily high temperature as long as it is matched between all the alchemical phases, but it may be simpler just to add a check to ensure that the `lambda=0` and `lambda=1` temperatures/pressures match within each phase.

**Comment by andrrizzi** [comment]
Thanks!

I can definitely add a temperatures/pressures check inside `AlchemicalPhase.create` before merging.

**Comment by andrrizzi** [comment]
Done! Merging (tagging @daveminh).

**Pull request merged**
