### PR TITLE
Remove functions exported to openmoltools

### PR DESCRIPTION
**Pull request by andrrizzi**
This will remove the Schrodinger's wrapper functions that have been exported to openmoltools in choderalab/openmoltools#195.

Should we update the conda recipe to include ``openmoltools-dev`` for now, or is there a release planned for ``openmoltools``?

### CODE REVIEW

**Comment by jchodera** [comment]
Feel free to use openmoltools-dev for now.

**Comment by davidlmobley** [comment]
I'd probably encourage doing a new point release for openmoltools soon. It:
a) has been a while
b) probably warrants doing on the basis of the schrodinger improvements
alone

Probably this is worth doing anytime there is any chance which is
significant and widely useful (i.e. to another of our labs) just on the
basis of conda issues alone (i.e. 'conda install openmoltools' will be what
most people on my end are using unless I tell them otherwise).

On Thu, Mar 3, 2016 at 2:03 PM, John Chodera <notifications@github.com>
wrote:

> Feel free to use openmoltools-dev for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/yank/pull/352#issuecomment-191985654>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by andrrizzi** [comment]
Also, I just checked and I can't find an ``openmoltools-dev`` for ``osx-64``, only for ``linux-64``.

I can work on creating a new release, if you agree. I never did it, but I'd like to get familiar with the process.

**Comment by jchodera** [comment]
Go ahead and cut a new release.  The process is:
* update the version number in [`setup.py`](https://github.com/choderalab/openmoltools/blob/master/setup.py#L27) to the new release number
* draft a new release from the [GitHub releases page](https://github.com/choderalab/openmoltools/releases)
* update [the `openmoltools` conda recipe in `conda-recipes`](https://github.com/omnia-md/conda-recipes/blob/master/openmoltools/meta.yaml#L3-L7) with the new release git tags and version number via a PR


To fix `openmoltools-dev`, I'll either have to update `.travis.yml` to build for `osx` as well or I will have to add a recipe to https://github.com/omnia-md/conda-dev-recipes

**Comment by davidlmobley** [comment]
Also, after release, you want to update the version tag in setup.py again so it doesn't look like you're continuing development on the released version.

**Comment by andrrizzi** [comment]
Thanks for the quick tutorial! I'll make release ``0.6.10`` and work on build ``openmoltools-dev`` on ``osx`` as well.

**Comment by andrrizzi** [comment]
Ah, no. I just saw that we were working for ``0.7.0``.

**Comment by jchodera** [comment]
Let me know if I need to do anything to help with this!

**Comment by jchodera** [comment]
Is this still in progress?

**Comment by andrrizzi** [comment]
I was going to wait to make a new release of `openmoltools` which I didn't have time to do yet, but I can set the conda recipe here on `openmoltools-dev` if you need this.

**Comment by jchodera** [comment]
I've already switched packages to `-dev` versions in a PR I'm about to open...

**Comment by andrrizzi** [comment]
Ok then go ahead and merge this if you want. I'll open a separate PR in case the tests won't pass. I didn't change the recipe yet so it shouldn't be conflicted.

**Comment by jchodera** [comment]
We may need [this fix](https://github.com/omnia-md/conda-recipes/pull/474/commits/439f0332a8f86b1fb2de122a032a5bdd9b629072) for `yank` or `openmoltools`:
```
+    - libgfortran 1.* # [linux and py35 and np == 19]
```
(Thanks @mpharrigan!)

**Comment by andrrizzi** [comment]
Thanks! I'm not sure that's the same problem because we get the error with all Python versions and because `ambermini` already set that requirement, but I can give it a shot without the `py35` flag.

**Comment by andrrizzi** [comment]
The tests pass locally (with `openmoltools-dev` on `os-x`), so if there are no objections I think I'll merge this and deal with eventual errors in a separate PR.

**Comment by jchodera** [comment]
Go for it!  The failure seems to be due to detection of Schrödinger tools not working properly.

**Pull request merged**
