### PR TITLE
Add YAML syntax for MCMC moves

### LINKED ISSUE #898: Allow to specify the MultiStateSampler and MCMCMoves in the YAML script
Picking up from the discussion in #863, what do you think about this?
```yaml
mcmc_moves:
    my-sequence-move:
        type: SequenceMove
        # Similarly to restraints, here go the __init__ arguments of the MCMCMove.
        move_list:
            - type: MCDisplacementMove
              # __init__ arguments of the nested MCMCMove.
              displacement_sigma: 1.5*nanometer
            - type: MCRotationMove
            - type: LangevinSplittingDynamicsMove
              n_steps: 500
              splitting: VRORV
    single-move:
        type: LangevinSplittingDynamicsMove
        timestep: 1.0*femtosecond

samplers:
    independent:
        type: MultiStateSampler
        # Here we can specify all the __init__ options.
        mcmc_moves: my-sequence-move
        number_of_iterations: 2000
        locality: 3
    repex:
        type: ReplicaExchangeSampler
        mcmc_moves: [single-move, single-move, my-sequence-move]
        number_of_iterations: 1000
        replica_mixing_scheme: swap-all
    sams:
        type: SAMSSampler
        state_update_scheme: local-jump

experiments:
    sampler: !Combinatorial [independent, repex]
    system: MySystem
    protocol: MyProtocol
    restraint: FlatBottom
```
I'd add the `samplers` and the `mcmc_moves` in two separate PRs (starting from the samplers).

I plan to set the defaults to use `ReplicaExchangeSampler` and 5000 iterations. Does this sound ok? Or do we want this to be a mandatory option?

### PR DESCRIPTION
**Pull request by andrrizzi**
Fix #898 .

For the existing global options that were injected into the MCMC move, I've kept `timestep` and `nsteps_per_iterations` (now `default_timestep` and `default_nsteps_per_iterations` respectively) because I thought these are options we'll have to change often, and I've deleted `collision_rate`, `mc_sigma_displacement` and `integrator_splitting` that I don't remember I ever had to change for production simulations. They can still be set in the `mcmc_moves` block, of course, but let me know if you think I should do things differently.

This requires choderalab/openmmtools#336 (and a new `openmmtools` release) for tests to pass.

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome! Can we specify `timestep` and `nsteps_per_iteration` in the MCMC block instead? I can see cases where we might use different blocks with different timesteps, so I'd prefer these being able to be specified in those MCMC blocks.

**Comment by andrrizzi** [comment]
It can be specified in both. The global options `default_timestep` and `default_nsteps_per_iterations` are used only if the default `MCMCMove` is used (i.e. if no `mcmc_move` is given in the `samplers` section).

Thanks for the reviews! I'll wait for tests to pass before merging.

**Comment by jchodera** [comment]
> The global options default_timestep and default_nsteps_per_iterations are used only if the default MCMCMove is used (i.e. if no mcmc_move is given in the samplers section)

Brilliant! Thanks!

**Comment by andrrizzi** [comment]
Uh! I just realized this wasn't merged.

**Comment by Lnaden** [comment]
Seems like an easy enough fix though, most all my changes were doc-related and I can make another pass though if something breaks.

**Pull request merged**
