### PR TITLE
Add `anisotrpic_dispersion_correction` and its cutoff to YAML options.

### LINKED ISSUE #483: Add option to control maximum allowed cutoff for fully interacting system and whether expanded system is used or not
Follows from discussion in #475 .

### LINKED ISSUE #641: Reducing the long-range cutoff properly
I have a pretty small system (48.  20.  34. A as the box dimensions). So the error that I am getting is:
```
  File "/root/anaconda2/envs/rezayank/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 4066, in __init__
    this = _openmm.new_Context(*args)
Exception: NonbondedForce: The cutoff distance cannot be greater than half the periodic box size.
```
I cannot make my system bigger, since I need to maintain the crystal periodicity. So one way would be to reduce the cut-off for long range interactions in the yaml file:
```
solvents:
  pme:
    nonbonded_method: PME # Main definition of the nonbonded method
    nonbonded_cutoff: 9*angstroms # Cutoff between short- and long-range interactions
    clearance: 16*angstroms
    positive_ion: Na+
    negative_ion: Cl-

# Define the systems: What is the ligand, receptor, and solvent we put them in
systems:
  # We can call our system anything we want, this example just uses a short name for the receptor hyphenated with the ligand
  model03nowat:
    # These names all use the names we defined previously
    phase1_path: [complex1.prmtop, complex1.inpcrd]
    phase2_path: [solvent.prmtop, solvent.inpcrd]
    ligand_dsl: resid 218 to 224
    # solvent_dsl: resname WAT  # optional
    solvent: pme
```
But it doesn't seem to affect anything at all. I set the size of the box using leap manually so the clearance is irrelevant here. But even though the cut-off is less than half of the box size, still I get the same error message. I even tried reducing it to a lesser value (like 5) to see whether it runs fine and I still got the same error. I am not sure if there is something wrong with my script, or is it because I prepare the files manually (even though I think I got the same issue by using the automated pipeline before), or Yank just disregards the cut-off value for some reason. I would appreciate your feedback!

### PR DESCRIPTION
**Pull request by Lnaden**
* Documented the `anisotrpic_dispersion_correction`
 * Added option for `anisotrpic_dispersion_cutoff`
 * Added test for AD_correction
 * Bumped YAML version
 * Bumped YANK minor version

Fixes #641, Fixes #483

### CODE REVIEW

**Comment by Lnaden** [comment]
If this looks good to merge, I'll merge. Do we also want to cut a new release to get this feature in?

**Comment by jchodera** [comment]
Can we cut a new point release for this when you get a chance, @Lnaden? I can then use it in orion!

**Comment by jchodera** [comment]
And thanks so much for getting this in!

**Comment by jchodera** [comment]
Tagging @davidlmobley since we need this for an orion calculation.

**Comment by Lnaden** [comment]
I'll get a release cut this afternoon!

**Comment by davidlmobley** [comment]
Thanks! Please let me know when this happens, @Lnaden - I'm guessing since John is on the road I might be the one ending up using it first.

**Comment by davidlmobley** [comment]
(Though, I'll also need to know how to modify the protocol being used for the calculations to make Yank use the smaller box that I understand this will enable...)

**Comment by Lnaden** [comment]
Just to update: I have the 0.15.2 release [staged](omnia-md/conda-recipes#724), but because of other issues on that channel, it can't publish. I have been working through those issues and will keep you posted.

**Comment by davidlmobley** [comment]
Thanks, @Lnaden . I have something ready to merge on conda-recipes as well that I also need for Orion, so it sounds like we need to get those resolved. I think we're also ready to run the calculations as soon as we can sort this out.

**Comment by Lnaden** [comment]
I saw those. I am waiting on a few other people's replies before I can advance those fixes since I am modifying their code, but I have added it to the cascade of builds to run to get everything built.

**Comment by davidlmobley** [comment]
@Lnaden - any headway on this? I'm giving a talk on Monday where I'd ideally be able to talk about some results of some (quick -- a few hours to a day?) calculations we would run after this is wrapped up.

**Comment by Lnaden** [comment]
Yes! Peter just approved the OpenMM Python 3.6 fix (~20 min ago) which had halted the process. Once that builds, I'll be firing off all the other PRs to build and let you know when yank 0.15.2 gets built

**Comment by davidlmobley** [comment]
Ooh, awesome! 

Since John is overseas -- can you get me some info (when 0.15.2 builds) on how I'd use the changes to set up hydration calculations with smaller box sizes? I'm tagging you again in the relevant orion issue.

**Comment by Lnaden** [comment]
Sure. I already have the documentation updated [here](http://getyank.org/0.15.2.dev0/yamlpages/options.html#yaml-options-anisotropic-dispersion-correction) and [here](http://getyank.org/0.15.2.dev0/yamlpages/options.html#yaml-options-anisotropic-dispersion-cutoff). 

The general box size when adding water is controlled through [the `clearance` option](http://getyank.org/0.15.2.dev0/yamlpages/solvents.html#yaml-solvents-clearance). I think what you need is to set the [`clearance`](http://getyank.org/0.15.2.dev0/yamlpages/solvents.html#yaml-solvents-clearance) option to something smaller (less water packed around the solute), then set  [`anisotropic_dispersion_correction: no`](http://getyank.org/0.15.2.dev0/yamlpages/options.html#yaml-options-anisotropic-dispersion-correction) so there is not the systems with the expanded nonbonded cutoffs. If I understand what you are trying to do, this should be what you need.

**Comment by andrrizzi** [comment]
I believe @davidlmobley is starting from an prepared `.xml` system. If this is the case, you can skip setting the `clearance` option since it is only used by the automated pipeline to add water molecules to the system.

**Comment by davidlmobley** [comment]
In this case we are not starting from prepared xml, no. What Levi was describing sounds like what I need.

**Comment by Lnaden** [comment]
@davidlmobley The travis-ci system is still having issues related to the Amazon S3 outage yesterday. I have both this PR and your [openmoltools PR](omnia-md/conda-recipes#727) running to see if there are any errors, but I can't look at the logs since the front end is down. Once I can confirm that they work correctly, I'll merge these in and let the recipes build and publish the changes.

**Comment by jchodera** [comment]
@davidlmobley : Once the package is pushed, you'll want to change this:

**Comment by davidlmobley** [comment]
@jchodera - your comment ends with "You'll want to change this:"  Was it cut off?
(I'm in a call, will catch up on messages soon.)

**Comment by Lnaden** [comment]
@davidlmobley Issue updates:

The YANK update has not been merged as the builds appear to just loop forever without error or indication as to why, but that might be due to the lingering S3 errors as there are some other oddities like corrupted downloads in the automated process.

Still working at it but no eta as the Travis people are "still working on it" as well

**Comment by jchodera** [comment]
Sorry, @davidlmobley---responded in slack instead.

**Comment by Lnaden** [comment]
@davidlmobley 

The Python 2.7 and 3.4 builds for YANK 0.15.2 are up. If you are using one of those versions of Python, you should have everything you need as I understand. Still figuring out where the 3.5 version is and 3.6 will be delayed by OpenMM at the moment.

Also, all Travis builds are currently down while they work on infrastructure, no ETA, so I guess its good we got even this.

**Comment by davidlmobley** [comment]
@Lnaden - it seems we require Python 3.5. Can you let me know when that shows up?

**Comment by Lnaden** [comment]
@davidlmobley the linux builds are up now. still working through the osx ones

**Comment by Lnaden** [comment]
@davidlmobley Just checking in to make sure I have all the critical updates in the `omnia` channel that you need uploaded before the weekend.

**Comment by davidlmobley** [comment]
@Lnaden - I'm going to see if I can try this today, unless @jchodera is able to. He got the Yank floe going on Orion before, and so I either need him to update his floe with this (so that it will run faster as was our goal) or do it myself. I'm assuming I'll need to do it myself and I plan to try that sometime today.

**Pull request merged**
