### PR TITLE
New states classes

### PR DESCRIPTION
**Pull request by andrrizzi**
This is the first big chunk of stuff for the new API. I've added a new module `states.py` implementing `ThermodynamicState`, `SamplerState` and `CompoundThermodynamicState`. The last one allows to extend `ThermodynamicState` by composition rather than inheritance and it will be used to mix `ThermodynamicState` with `AlchemicalState`. I've added a lot of documentation and tests so hopefully it should be clear and it shouldn't introduce new bugs.

Nothing is attached to the main code yet. Before doing it, I need to adapt `alchemy.AlchemicalState`, and if we want to directly move to a scheme that uses `MCMoves`, I'll also add a `ContextCache`. Next thing is to write the first implementation of the lower level `Storage` class.

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome!

Can we chat about this briefly late today?

**Comment by andrrizzi** [comment]
Sure! I forgot to add that I still need to make few more changes. I'd like to add automatic treatment of the thermostat, if I find a way to squeeze it in.

**Comment by andrrizzi** [comment]
Done! Ready for review. Nothing is attached to the code yet. It just adds a new `states.py` module with tests. The stuff left in QuantifiedCode are quite useless, and one of them suggest me to introduce a bug!

In a separate PR I'll create a new `cache.py` for the global context cache.

**Comment by andrrizzi** [comment]
Closing this since this has been moved to `openmmtools`.

**Pull request closed without merging**
