### PR TITLE
Trying to get AWS doc upload to work under new username

### PR DESCRIPTION
**Pull request by pgrinaway**
Added secure environment variables, changed `push-docs-to-s3.py` to use s3cmd.

### CODE REVIEW

**Comment by pgrinaway** [comment]
Looks like it's passing, but there's still an issue with AWS upload...

**Comment by rmcgibbo** [comment]
Secure environment variables aren't available on PRs. Only on the master branch. Otherwise someone could use a PR to your repository to steal the private keys.

**Comment by pgrinaway** [comment]
They are available on PRs from [branches in the master](http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests) repo, though, which is what I am doing here:

**Comment by rmcgibbo** [comment]
Oh, cool.

**Comment by pgrinaway** [comment]
Unless I'm misreading what I linked, which is a possibility, though the Travis build does seem to be [setting the environment variables](https://travis-ci.org/choderalab/yank/builds/47963636#L86-L87). An upload seems to work fine on my local machine; perhaps the docs are not where we think they are?

**Comment by bas-rustenburg** [comment]
Am I misreading things, or did your travis log show you run the `after_sucess` twice?

**Comment by bas-rustenburg** [comment]
https://travis-ci.org/choderalab/yank/builds/47963636#L1437

and 

https://travis-ci.org/choderalab/yank/builds/47963636#L1739

**Comment by kyleabeauchamp** [comment]
Yes.  The error is in the `.travis.yml`.  It's in there twice.

**Comment by pgrinaway** [comment]
ok, hang on, let me fix that.

**Comment by pgrinaway** [comment]
Hm, [this](https://travis-ci.org/choderalab/yank/builds/47973646#L1770) is interesting. Perhaps there is something wrong with the environment variables...

**Comment by pgrinaway** [comment]
May be related to #170 changes. I can't modify the bucket permissions anymore...I will switch back to my own EC2 account later tonight to continue debugging, then when we resolve all the other issues we can revert to a choderalab EC2 account.

**Comment by pgrinaway** [comment]
Restarting the build

**Comment by pgrinaway** [comment]
The build is now successfully pushing docs to S3! Woo! I will configure the static website hosting later...

**Comment by jchodera** [comment]
Woohoo!

**Pull request merged**
