### PR TITLE
[WIP] Attempting to fix nosetests on travis

### PR DESCRIPTION
**Pull request by jchodera**
Trying to figure out what is going on...

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
So the build already runs the tests, so I don't think we need to separately run nose tests.

**Comment by kyleabeauchamp** [comment]
OK, so I see you moved the tests back out of the recipe.

**Comment by jchodera** [comment]
> So the build already runs the tests, so I don't think we need to separately run nose tests.

That wasn't working---the tests are failing for some reason I don't understand (since they work on my machine).  I've moved them out of the build recipe, possibly temporarily.

**Comment by jchodera** [comment]
Wait a sec---I *do* see these failures on my laptop during a conda build, but not when I run standalone nosetests.  I'm still not sure where the errors in #187 are coming from.

**Comment by jchodera** [comment]
Deprecated; fixing through a new PR based on @kyleabeauchamp's suggestion from #187.

**Pull request closed without merging**
