### PR TITLE
Begin removing extraneous code from setup.py/cleaning up

### PR DESCRIPTION
**Pull request by pgrinaway**
Removed the `check_dependencies` function and the call to it to address #93

### CODE REVIEW

**Comment by pgrinaway** [comment]
Not sure what the deal with that error in Travis is, but I think it is probably for a separate PR (given that it has been occurring in previous builds)

**Comment by jchodera** [comment]
Yeah, there are some things we need to fix in separate PRs.

**Comment by pgrinaway** [comment]
Ok, otherwise I think this is all that had to happen with setup.py? Correct me if I'm wrong...

**Comment by pgrinaway** [comment]
@jchodera @kyleabeauchamp am I missing something else that we wanted to do here or is this ready to merge? I think that we only needed to remove the dependency check, right?

**Comment by jchodera** [comment]
I think that's it, right?

**Comment by kyleabeauchamp** [comment]
Lgtm

**Comment by pgrinaway** [comment]
Ok, I'm going to go ahead and merge this and take care of the travis error in a future PR.

**Pull request merged**
