### PR TITLE
Store topology, write trajectory

### LINKED ISSUE #309: Store serialized OpenMM Topology objects in NetCDF store files
It would be helpful for generating visualizations and trajectories to store the OpenMM `Topology` objects corresponding to each phase as serialized objects in the NetCDF store files.

### PR DESCRIPTION
**Pull request by andrrizzi**
Fix #309, #379 and #375.

I couldn't find a way to serialize the OpenMM `Topology` object without pickling, so I saved instead the MDTraj topology. I basically saved the arguments of `mdtraj.Topology.from_dataframe()` needed to recreate the topology into a JSON string. At least the representation will be constrained by the API and it won't break every time someone changes the implementation of `Topology`.

### CODE REVIEW

**Comment by jchodera** [comment]
I think mdtraj will serialize the Topology into JSON for you automatically.
It does this for HDF5 storage. See

http://mdtraj.org/latest/hdf5_format.html#topology

**Comment by andrrizzi** [comment]
Yeah, that was my first attempt. Unfortunately, I don't think it does it automatically. That format is implemented manually in the `HDF5TrajectoryFile` class [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/hdf5.py#L304-L380) and it stores the representation directly into an HDF5 file. I couldn't find any method exposed by `Topology` object to serialize it automatically.

**Comment by jchodera** [comment]
Ah, OK!

Maybe we should post in the OpenMM issue tracker to see if we can get serialization capability eventually migrated into OpenMM proper?

Thanks!

**Comment by andrrizzi** [comment]
Will do!

**Comment by andrrizzi** [comment]
I've added the command `yank analyze extract-trajectory` based on a function I've implemented some time ago. I tested it on a local netcdf file and it works well.

Feel free to merge if you approve the choice of the command name and tests passed.

Tomorrow I'll cut out a new release.

**Comment by andrrizzi** [comment]
I'll add the commits for the new release here as I want to test these changes too with the fixed-version recipe.

**Comment by andrrizzi** [comment]
Ok! I'll merge this and test a couple of examples with the next `yank-dev` on the cluster before releasing on `conda-recipes`.

**Pull request merged**
