### PR TITLE
Update conda dev recipe to use pinned versions for 0.8.0 release

### PR DESCRIPTION
**Pull request by jchodera**
See #369

### CODE REVIEW

**Comment by jchodera** [comment]
Travis is failing because somehow `openmm-dev` is still being brought in:
https://travis-ci.org/choderalab/yank/builds/127249181#L1592

Any ideas why @andrrizzi?  Does one of the other tools with pinned versions require `openmm-dev`?

**Comment by andrrizzi** [comment]
I think `openmmtools-dev` in the test dependencies requires `openmm-dev`. Also, I'm not sure what happens during travis tests, but `openmoltools-dev` in the run dependencies requires `openmm-dev` as well.

**Comment by jchodera** [comment]
Thanks for catching that!

**Comment by andrrizzi** [comment]
No problem! I think there's still [this line](https://github.com/jchodera/yank/blob/master/devtools/conda-recipe/meta.yaml#L57) to correct.

**Comment by jchodera** [comment]
Thanks!  Fixed.

**Comment by andrrizzi** [comment]
Ah! We need to release `openmoltools 0.7.0` to release `yank` because we need the new `schrodinger` module. We already have a PR for that on `conda-recipes`. I'll see if tests pass there and we can proceed.

**Comment by jchodera** [comment]
Thanks, @andrrizzi!

**Comment by jchodera** [comment]
Looks like you cut `openmoltools` 0.7.0 already.  Do you want to update the [conda recipe](https://github.com/omnia-md/conda-recipes/tree/master/openmoltools) or should I?

**Comment by jchodera** [comment]
Tests pass. I think we can cut a new release now.

**Pull request merged**
