### PR TITLE
Always use OpenEye charges instead of sqm when OE toolkit is available

### PR DESCRIPTION
**Pull request by andrrizzi**
As per title. Should be ready to be merged.

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

I worry that autodetection of OpenEye and selecting behavior based on this can cause unexpected differences in runs if OpenEye is misconfigured or not installed or the license file is not current.

What about adding an option to the YAML file, or changing the charge model to `openeye-am1bcc` to select this?

**Comment by andrrizzi** [comment]
I see. What if I changed a little the syntax to be
```yaml
molecules:
   benzene:
      name: benzene
      parameters: openeye-am1bcc  # this means openeye charges + antechamber
```
Or maybe it's better ``parameters: openeye-antechamber``?

There is currently no syntax to explicitly separate parametrization of charges from other parameters, but we can add it if that's preferable.

**Comment by jchodera** [comment]
How about openeye:am1bcc-gaff?

**Comment by andrrizzi** [comment]
Sounds great.

**Comment by andrrizzi** [comment]
Done!

**Comment by jchodera** [comment]
Looks good!

**Pull request merged**
