### PR TITLE
Use MBAR for enthalpy and clean up analyze workflow

### PR DESCRIPTION
**Pull request by Lnaden**
Addresses #466 and some todos in the analyze.py script.

* Enthalpy now computed from MBAR instead of just mean energy.
* Changed workflow to reduce duplicate code for decorrelating samples and to prevent having to create multiple MBAR objects.
* Added cascading functions in workflow so if any particular step is forgotten, the pre-requisite steps will be called.
  - Equilibration calculation is not part of cascade yet.

### CODE REVIEW

**Comment by Lnaden** [comment]
I have not been able to test all functionality yet, so there may be a few bugs still.

**Comment by jchodera** [comment]
This looks like a big improvement! 

We should sort out what we want to do with the analysis framework. We've given very little thought to this so far, but will need to make it scale up to analyze a large number of simulations. The current structure isn't very amenable to that.

Just brainstorming now---we can move this to an issue later---but I'd love to see:
* an `Analysis` class that contains all the methods and data, and is initialized with a YANK calculation directory
* a cleaner analysis API---it's OK if this breaks backward-compatibility
* some facility for analyzing a batch of simulations that have been set up in some directory tree

**Comment by jchodera** [comment]
I've just fixed the travis test issue. You should update or rebase from `master` when you get a chance so the travis tests will run.

**Comment by jchodera** [comment]
@Lnaden : I'm going to make some commits to this branch to clean things up a bit.

**Pull request merged**
