### PR TITLE
[WIP] Use MDTraj DSL to specify ligand atoms.

### PR DESCRIPTION
**Pull request by andrrizzi**
This address #161 .

I changed the parameter --ligname=RESNAME [default: MOL] to --ligdsl=LIGANDDSL [default: “resname MOL”] that takes a DSL string.

I wanted to call the parameter simply ligand but it’s in conflict with systembuilder --ligand and I got the error "docopt.DocoptLanguageError: --ligand is not a unique prefix: --ligand, --ligand?".

Should I change its name to something else? "--ligatoms=DSLSTRING" ? Or maybe change the name of the parameter for systembuilder?

Once the name is settled, I'll change also the syntax in the documentation, the examples and nosetests.

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome!

**Comment by jchodera** [comment]
We might want to temporarily deprecate the `SystemBuilder` CLI for now, since it's clear we need to rethink it to some degree.

@pgrinaway : What do you think?

**Comment by andrrizzi** [comment]
Nosetests passed locally. There were also a couple of wrong ligand res names in the examples so I fixed them. Now resolving conflicts and merging.

**Comment by jchodera** [comment]
Thanks!

**Comment by andrrizzi** [comment]
Can we close this? Is there anything else that must be implemented to address this?

**Pull request merged**
