### PR TITLE
[WIP] Run experiments starting from system files

### LINKED ISSUE #372: Peptide ligand does not have "net_charge"
Re: convo with @andrrizzi yesterday; I expect this would happen with any setup with a peptide, but I can provide my input files if they are specifically needed to recreate the error!  

Error message:
```
Traceback (most recent call last):
  File "/home/behrj/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/home/behrj/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/home/behrj/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 34, in dispatch
    yaml_builder.build_experiment()
  File "/home/behrj/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1270, in build_experiment
    self._run_experiment(combination, output_dir)
  File "/home/behrj/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1858, in _run_experiment
    system_pars, ligand_descr['net_charge'])
KeyError: 'net_charge'
```

### LINKED ISSUE #384: Add capability to start from prmtop inpcrd in YAML script
Continuing the discussion started in #380 .

I think I can easily accomodate in the YAML syntax the possibility of starting from a `prmtop`, `inpcrd` pair. **This would also give us an exit for every possible user case not currently supported by the automatic pipeline**. Something like
```yaml
experiments:
  system:
    complex: 'setup/complex.prmtop' # yank look for inpcrd in the same folder
    solvent: 'setup/solvent.prmtop'
    ligand_dsl: 'resname MOL'
    solvent: RF # we need some info about the solvent to pass to OpenMM
  protocol: absolute-protocol
```
Once this is set, we can let `yank prepare` automatically generate the correct YAML script.

The user could specify both `system` and `components`, for example
```yaml
experiments:
  system:
    complex: 'setup/complex.prmtop'
    solvent: 'setup/solvent.prmtop'
    ligand_dsl: 'resname MOL'
    solvent: RF
  components:
    receptor: abl
    ligand: imatinib
    solvent
  protocol: absolute-protocol
```
would run 2 calculations.

In general, I think we should see the automatic setup as an extra feature, not as something the user has to go through.

### PR DESCRIPTION
**Pull request by andrrizzi**
* Fix #384: _Add capability to start from prmtop inpcrd in YAML script_.
* Partially address #410 by moving the system pipeline specification outside of experiments.
* Fix #372: _Peptide ligand does not have "net_charge"_. This is necessary to perceive the charge of the ligand in the `prmtop` file, and alchemically modify the correct number of counterions.
* Add capability to start from gromacs files in YAML script. This is a simple enough extension.

### CODE REVIEW

**Comment by andrrizzi** [comment]
I just need to mark one test as 'slow' to fix the tests, but this is ready to be merged!

Few examples with the current valid syntax
```yaml
...

systems:
    amber_example:
        complex_path: [dir/complex.prmtop, dir/complex.inpcrd]
        solvent_path: [dir/solvent.prmtop, dir/solvent.inpcrd]
        ligand_dsl: resname MOL
        solvent: PME
    gromacs_example:
        complex_path: [dir/complex.top, dir/complex.gro]
        solvent_path: [dir/solvent.top, dir/solvent.gro]
        ligand_dsl: resname MOL
        solvent: PME
        gromacs_include_dir: dir/include/
    pipeline_example:
        receptor: Abl
        ligand: imatinib
        solvent: PME

experiments:
    system: !Combinatorial [amber_example, gromacs_example, pipeline_example]
    protocol: absolute-binding
```

**Comment by jchodera** [comment]
> Few examples with the current valid syntax

This is awesome, BTW!

I see we still have the old command-line examples, like `examples/benzene-toluene-explicit/run.sh`---will those be deprecated and removed in a future PR?

**Comment by andrrizzi** [comment]
> will those be deprecated and removed in a future PR

Yes, that's the plan. I wanted to consolidate the YAML syntax before changing all examples to save time.

**Comment by jchodera** [comment]
Thanks! Merge when ready!

**Comment by andrrizzi** [comment]
Awesome! Merging.

**Pull request merged**
