### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by jchodera**
This is just a little experimental test for adding a Dockerfile.

### CODE REVIEW

**Comment by jchodera** [comment]
This should be ready for review. After merging, I'd create an experimental docker hub project so that users could pull down `yank` images via
```bash
docker run -i -t jchodera/yank
```
Again, this is experimental, but should work for now.

**Comment by andrrizzi** [comment]
I don't know much about docker, but this looks good to me!

**Comment by jchodera** [comment]
Let me add some notes about using the docker version in a separate PR after
more testing.

**Comment by andrrizzi** [comment]
Sure! Feel free to merge if ready.

**Comment by jchodera** [comment]
Oh! This was never merged.

Is it too late to get this into 0.11.0?

**Comment by andrrizzi** [comment]
Still in time I think! I'm merging this now.

**Pull request merged**
