### PR TITLE
Release 0.23.4

### PR DESCRIPTION
**Pull request by andrrizzi**

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like there's a test failure:
```

======================================================================
FAIL: Test each of the steps of the MBAR creation process
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/yank-0.23.4-py3.6-linux-x86_64.egg/yank/tests/test_analyze.py", line 320, in test_mbar_creation_process
    assert u_sampled.shape == (self.n_replicas, self.n_states, self.n_steps)
AssertionError: 
-------------------- >> begin captured logging << --------------------
yank.multistate.multistateanalyzer: INFO: Reading energies...
yank.multistate.multistateanalyzer: INFO: Done.
--------------------- >> end captured logging << ---------------------
```

**Comment by andrrizzi** [comment]
That's the usual `analyze` test that sometimes fails because of slow convergence, but there should be no problems with the code.

**Comment by jchodera** [comment]
Ah, thanks!

I guess we should fix that test at some point. I'll create an issue!

**Comment by andrrizzi** [comment]
Thanks! I'll proceed with the bugfix release then!

**Pull request merged**
