### PR TITLE
Convert Abl:imatinib example to use YAML

### PR DESCRIPTION
**Pull request by jchodera**
This is based on the YAML file @sonyahanson and @andrrizzi prepared.

### CODE REVIEW

**Comment by jchodera** [comment]
This currently fails with
```
[chodera@gpu-1-8 abl-imatinib-explicit]$ mpirun -configfile configfile
LOG: eval() arg 1 must be a string or code object
Traceback (most recent call last):
  File "/cbio/jclab/home/chodera/miniconda/bin/yank", line 9, in <module>
    load_entry_point('yank==0.9.0', 'console_scripts', 'yank')()
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/cli.py", line 105, in main
    dispatched = getattr(commands, command).dispatch(args)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/commands/script.py", line 33, in dispatch
    yaml_builder = YamlBuilder(yaml_source=args['--yaml'])
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1164, in __init__
    self._parse_options(yaml_content)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1261, in _parse_options
    self.options.update(self._validate_options(temp_options))
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/yank-0.9.0-py2.7-linux-x86_64.egg/yank/yamlbuild.py", line 1217, in _validate_options
    raise YamlParseError(str(e))
yank.yamlbuild.YamlParseError: eval() arg 1 must be a string or code object
```
but I'm not quite sure exactly what is triggering the failure.

**Comment by andrrizzi** [comment]
Sorry for the poor error output, I'll have it fixed soon. It looks like there is an options that it cannot find automatically in yank, repex nor alchemy. Can I just take a look at it tomorrow? Unfortunately I've not much time now.

**Comment by andrrizzi** [comment]
Just a first (probably pointless) guess: I would check if the `alchemy` package is up-to-date. I suspect it has troubles finding the new option `softcore_beta` in the constructor of `AbsoluteAlchemicalFactory`.

**Comment by jchodera** [comment]
> Sorry for the poor error output, I'll have it fixed soon. It looks like there is an option that it cannot find automatically in yank, repex nor alchemy. Can I take a look at it tomorrow? Unfortunately I've not much time now.

No problem!  Thanks for the help!

**Comment by jchodera** [comment]
You were right! There was an installation problem with `alchemy-dev` that is fixed now. 

The run produced some output in `experiments.log` that was puzzling (but not urgent!):
```
2016-03-30 21:24:26,089 - INFO - yank.yamlbuild - Setting up the system for Abl, PME and STI
2016-03-30 21:39:23,775 - ERROR - yank.yamlbuild - Found charged ligand but no indications for ions in solvent PME
```
Note that `CutoffPeriodic`, not `PME`, was specified.

Meanwhile `experiments_1.log` through `experiments_3.log` say things like
```
2016-03-30 21:24:26,079 - DEBUG - yank.yamlbuild - Node 3/4: MPI barrier - waiting for the simulation to be created.
``` 
and are still waiting on Note 0/4 (which has terminated, I think).

We'll need to find some way to have the master gracefully terminate the MPI job on failures.

**Comment by jchodera** [comment]
Huzzah!

**Comment by jchodera** [comment]
This seems to be working for me on the cluster too.

**Pull request merged**
