### PR TITLE
Add serialization to the notebooks

### PR DESCRIPTION
**Pull request by Lnaden**
Also renders no mater what format you specify

### CODE REVIEW

**Comment by jchodera** [comment]
Is this something we should get into the SAMS PR before release?

**Comment by Lnaden** [comment]
Yes, its a very small fix to enable something that is already in the notebooks. I just had to modify the CLI file

**Comment by Lnaden** [comment]
This should very few issues with #915, but I see the few it is. Merge done

**Comment by andrrizzi** [comment]
Yeah, no worries! This will be easy to resolve.

**Pull request merged**
