### PR TITLE
Allow running hydration free energy calculations

### PR DESCRIPTION
**Pull request by andrrizzi**
Waiting for tests to pass.

An example of current syntax
```yaml
molecules:
  toluene:
    name: toluene
    parameters: antechamber

solvents:
  vacuum:
    nonbonded_method: NoCutoff
  PME:
    nonbonded_method: PME
    nonbonded_cutoff: 1*nanometer
    clearance: 1*nanometer
    positive_ion: Na+
    negative_ion: Cl-

systems:
  hydration_example:
    solute: toluene
    solvent1: PME
    solvent2: vacuum

protocols:
  my_protocol:
    ...

experiments:
  system: hydration_example
  protocol: my_protocol
```

### CODE REVIEW

**Comment by andrrizzi** [comment]
Tests pass! This is ready to be merged.

Yank still uses hardcoded `complex` and `solvent` phases, even for hydration free energy calculations. I'll implement arbitrary phase names in the next PR.

**Comment by andrrizzi** [comment]
To be clearer, this _does not_ reintroduce solvation free energies into Yank, but only allows automatic setup.

**Comment by jchodera** [comment]
Looks awesome!

**Comment by andrrizzi** [comment]
Great! Merging.

**Pull request merged**
