### PR TITLE
New automatic parameterization scheme for FlatBottom and various small fixes

### PR DESCRIPTION
**Pull request by andrrizzi**
- Save NaN logs into experiment folder. This avoids multiple experiments running in parallel to overwrite files generated for previous failures.
- Setup all systems even if experiments are not specified. This way it's easier to use the pipeline just to setup up systems.
- Fix experiment log file name when running a list of experiments in the YAML script.
- Raise an error if restraint shell volume is bigger than system volume when computing the standard state correction.

### CODE REVIEW

**Comment by andrrizzi** [comment]
One of the test cases using the `FlatBottom` restraint is now failing because of the new volume check. I'll have to implement in this PR the new automatic parameterization scheme we discussed before merging.

**Comment by andrrizzi** [comment]
I had to push the fix for #803 here because I needed all in one place to continue my simulations. I'll implement today the new `FlatBottom` automatic parameterization so that I can merge this.

I've moved the option `integrator_splitting` from being an `AlchemicalPhaseFactory` option to be an `ExperimentBuilder` option since it's used in `ExperimentBuilder._build_experiment`. `AlchemicalPhaseFactory.initialize_alchemical_phase` now uses the first integrator move in the sampler for equilibration (with appropriate collision rate and number of steps).

**Comment by andrrizzi** [comment]
Ok! This should be ready now.

**Comment by Lnaden** [comment]
Should be fine! go for it

**Comment by andrrizzi** [comment]
Thanks!

**Pull request merged**
