### PR TITLE
Serialize System, State, and Integrator on NaN fail during propagation, 0.15.0

### PR DESCRIPTION
**Pull request by jchodera**
This causes the `System`, `State`, and `Integrator` to be serialized when YANK fails due to `NaN`s in order to aid debugging.

Testing this now.

### CODE REVIEW

**Comment by jchodera** [comment]
I wonder if we should add a test that uses a too-large timestep to force failure?

**Comment by jchodera** [comment]
@Lnaden : Looks like the test failure was stochastic. Let's merge this and get out a new minor version increment?

**Comment by Lnaden** [comment]
We could just update the version number on this PR. Are you wanting to cut a new release based on this?

**Comment by jchodera** [comment]
I think it would be useful to help other folks debug.

Can you update the version number in a separate PR?

**Comment by Lnaden** [comment]
Yes, but is there any harm in doing it on this one? Since its a branch off the main repo, I can just pull down and edit it

**Comment by jchodera** [comment]
Whatever floats your boat.

**Comment by Lnaden** [comment]
Okay, this should be prepped for release if the changes I made look good

**Pull request merged**
