### PR TITLE
Critical bugfixes for SAMS release

### PR DESCRIPTION
**Pull request by jchodera**
This fixes bugs in two of the features I added to the SAMS release:
* Cray detection now correctly checks environment variables instead of static list of possible MPI environment variables (whoops!)
* FIRE minimization debug message now correctly prints `max_iterations` instead of nonexistent variable

### CODE REVIEW

**Comment by jchodera** [comment]
@Lnaden : We're still having trouble with the `test_analyze.py:TestMultiPhaseAnalyzer` tests failing due to `nan`s in travis tests. Maybe we can merge this and look into that separately?

**Comment by Lnaden** [comment]
Thats on my todo list today. It only recently starting having that problem so I'll dig into whats changed

**Comment by Lnaden** [comment]
I'm trying to replicate the tests locally but I can't. Can either of you, @andrrizzi or @jchodera ?

**Comment by andrrizzi** [comment]
Yeah, I was able to reproduce locally. It seems to happen only with the SAMS test suites.

**Comment by andrrizzi** [comment]
Maybe we can just try to use what I suggested in #931 (using `equal_nan=True`, it's False by default).

**Comment by Lnaden** [comment]
I don't like setting `equal_nan=True` because I'm worried that it will mask errors we should actually handle.

**Comment by Lnaden** [comment]
Those tests should never throw a `nan` and if we do, thats something to look into.

**Comment by Lnaden** [comment]
Okay! I found the bug. Its stochastic from MBAR estimating free energy between identical, unsampled states with very low number of samples (~< 10). I have increased the number of default samples while also making the tests more robust.

I also found a bug in the additional test samples loop where the criteria to stop after X cycles didn't actually stop the cycle. Whoops.

This should fix both the `MultiStateAnalyzer` test bug and the MBAR creation test bug.

**Comment by Lnaden** [comment]
Tests finally pass. We are approaching the upper limit of travis run time tests, so we may want to think about figuring a way to make some tests faster, or at least split them up.

One ideas is the `test_experiment.test_charged_ligand` which takes > 40% of the total test time, thats probably the place I would start

**Comment by andrrizzi** [comment]
> One ideas is the `test_experiment.test_charged_ligand` which takes > 40% of the total test time, thats probably the place I would start

Wow! We can probably change the tested molecules to smaller molecules. As long as they have the same charge, it will still test what we want.

**Comment by Lnaden** [comment]
Is it possible to do counterion addition in vacuum by force? Right now its doing it in explicit + PME, so that is probably what the slow part is

**Comment by andrrizzi** [comment]
I think so! I thought the bottleneck was charging `imatinib` in the setup pipeline, but it could be adding the explicit solvent.

**Comment by Lnaden** [comment]
Was there anything else needed for this pr?

**Comment by jchodera** [comment]
Nope!

**Pull request merged**
