### PR TITLE
Updated conda recipe to install mpi4py

### PR DESCRIPTION
**Pull request by jchodera**
This is to keep in sync with the [conda recipe](https://github.com/omnia-md/conda-recipes/pull/128).

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
LGTM.  failure is just the old LJ fluid segfault, may require some package rebuilds.

**Comment by jchodera** [comment]
I thought I had rebuilt the packages. Did we forget to change some version numbers?

**Comment by jchodera** [comment]
Or increment build numbers to get jenkins to replace existing binstar files?

**Comment by rmcgibbo** [comment]
Right. Need to increment.

**Comment by jchodera** [comment]
Done with with #129.

**Pull request merged**
