### PR TITLE
Suppress Epik output/error messages.

### PR DESCRIPTION
**Pull request by bas-rustenburg**
This suppresses any stderr/stdout messages that epik produces.

### CODE REVIEW

**Comment by andrrizzi** [comment]
Nice! Are there errors in epik that we want to catch for which ``check_call()`` does not raise ``CalledProcessError``?

**Comment by bas-rustenburg** [comment]
I haven't extensively tested all that Epik can do, but I could try making epik fail and seeing whether this catches it.

**Comment by andrrizzi** [comment]
I'm checking the [manual](https://isp.ncifcrf.gov/files/isp/uploads/2010/07/epik20_user_manual.pdf). I wonder if the options ``–NO_JOBCONTROL`` does it.

**Comment by bas-rustenburg** [comment]
Good call! I think that might also work, and leaves any other warnings that may be of interest.

**Comment by bas-rustenburg** [comment]
Nicer solution, added in new commit. Good to merge if checks pass.

**Comment by bas-rustenburg** [comment]
Whoops, left something behind. Fixing.

**Comment by andrrizzi** [comment]
Looks good to me.

**Pull request merged**
