### PR TITLE
Fix #954: MultiStateSampler.run(None) doesn't work when resuming.

### LINKED ISSUE #954: Sampler's run method doesn't work correctly when the n_iteration argument is not specified
If `n_iterations` is `None`, the current algorithm compute incorrectly the maximum iteration, and it run for a shorter time than specified (if it runs at all). This affects the ability to resume through the API, although it doesn't affect resuming through the YAML interface since we always pass `n_iteration`.

I'll open a bugfix PR soon.

### PR DESCRIPTION
**Pull request by andrrizzi**

### CODE REVIEW

**Comment by Lnaden** [comment]
Won't this fail if someone has just stopped a simulation but not collapsed it? E.g. if someone did `.run(50)` and then `.run(None)`, then it will run for the full number of iterations in addition to the 50

**Comment by andrrizzi** [comment]
> then it will run for the full number of iterations in addition to the 50

Hmm. I think `sampler._is_completed(None)` just checks that `sampler.iteration >= sampler.number_of_iterations` so it should behave as expected and stop at `number_of_iterations`.

**Comment by Lnaden** [comment]
Okay, then that will work. I think there is some duplicated checking going on there, but its fine as is

**Comment by andrrizzi** [comment]
Ok, thanks for the review!

**Pull request merged**
