### PR TITLE
Fix extract_trajectory from nc file

### PR DESCRIPTION
**Pull request by andrrizzi**
The function was broken when we broke backwards compatibility of ReplicaExchange storage format.

This is only a quick and dirty solution since we have other priorities. We should rewrite this after the analysis API will be stable.

### CODE REVIEW

**Comment by andrrizzi** [comment]
@Lnaden can you take a look at the error I'm getting with Python 3.4 tests? I think it's related to the changes in the openeye license checks in #666, and I wonder if you already know what is it about. Otherwise, I'll try to track it down.

**Comment by Lnaden** [comment]
Ill take a look

**Comment by Lnaden** [comment]
I think I have the fix, let me pull this PR and add it here

**Comment by Lnaden** [comment]
Well that didn't work. Give me a bit, I'll try to fix it for you

**Comment by andrrizzi** [comment]
Thanks!

**Comment by Lnaden** [comment]
Okay, that should fix it

**Comment by Lnaden** [comment]
Woo! That fixed it and should also fix the nightlies when this gets merged in

**Comment by andrrizzi** [comment]
Awesome! Thanks!

**Pull request merged**
