### PR TITLE
Attempting fix at ambermini 16 issues

### LINKED ISSUE #541: Update tests and dependencies for AmberMini 16
Some tests are failing as I think they are looking for old FF files which got moved in AmberMini v16. 

We will need to update tests, and version dependency of ambermini in YANK.

I'll make a PR soon for this.

### PR DESCRIPTION
**Pull request by Lnaden**
Patches in AmberMini v16 requirements and points moved FF files

Fixes #541

### CODE REVIEW

**Comment by Lnaden** [comment]
These tests are now passing, approval needed

**Comment by jchodera** [comment]
Looks good to me.

In future updates, I wonder if we should pick a mix of forcefields for the tests, or perhaps add a test specifically to try a few forcefields for a small system.

**Comment by Lnaden** [comment]
I don't think thats something that should go into functionality tests for YANK. We mainly want the tests to make sure everything works. I think comparing FFs in YANK should be handled somewhere else, doing it in tests may add a long time to the tests themselves.

**Comment by jchodera** [comment]
OK, works for me.

**Pull request merged**
