### PR TITLE
Anisotropic dispersion correction

### LINKED ISSUE #339: Anisotropic dispersion correction
This is just a reminder to implement the long-range [anisotropic dispersion correction](http://dx.doi.org/10.1021/jp0735987).

### PR DESCRIPTION
**Pull request by andrrizzi**
This continue the work in #371 to implement anisotropic long range dispersion correction.

Fix #339 .

### CODE REVIEW

**Comment by andrrizzi** [comment]
I've been digging into pymbar interface and code to understand what's the best way to do this.

I think I just have to use the function `mbar.computePerturbedFreeEnergies(u_kn)` where `u_kn` is the `1 x nreplicas x niterations` array containing the energies of the fully interacting state. Is that correct?

**Comment by andrrizzi** [comment]
Ah, no I misunderstood the interface. For that to work the number of states must be equal to the original one. Will keep digging.

**Comment by jchodera** [comment]
Let me tackle that part in a separate PR! It's nontrivial.

**Comment by andrrizzi** [comment]
Ok! Feel free to merge this if think the changes are good then!

**Comment by andrrizzi** [comment]
If it's just implementing in python formula (8) of the manuscript I think I can handle it if you don't have much time. Otherwise I'll work on setting up validation.

**Comment by jchodera** [comment]
No, it's reworking the input `u_kln` matrix to add another state from which no samples were drawn. Should be easy. I can do it now!

Will merge this right away and you can move onto other things!

**Comment by andrrizzi** [comment]
Thanks!

**Pull request merged**
