### PR TITLE
Fix handling of periodic boundary conditions for non-periodic systems

### LINKED ISSUE #398: Debug replica exchange harmonic oscillator test failures

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #398

### CODE REVIEW

**Comment by jchodera** [comment]
The positions in `ReplicaExchagne` were being retrieved by `getState(getPositions=True,enforcePeriodicBoundaries=True)`, which would wrap particles in non-periodic systems by accident. This now selects whether or not periodic boundaries should be enforced based on whether the system is periodic or not.

**Comment by jchodera** [comment]
This should be ready to review and merge, @andrrizzi.

(Replica exchange tests pass locally.)

**Comment by jchodera** [comment]
Woohoo!  Travis tests pass.

**Comment by andrrizzi** [comment]
Awesome! Looks good! Merging.

**Pull request merged**
