### PR TITLE
Remove the deprecated multistate and mpi packages

### PR DESCRIPTION
**Pull request by andrrizzi**
In this PR, I have removed `yank.multistate.*` and `yank.mpi` that have been deprecated and moved to `openmmtools` and `mpiplus` respectively.

### CODE REVIEW

**Comment by andrrizzi** [comment]
It looks like there's a small import error in `openmmtools` so this will have to wait for a bugfix release before tests can pass. This can wait anyway. We should also move `test_analyze.py` to `openmmtools`.

**Comment by jaimergp** [comment]
> -10,816 

That's lovely (L)

**Comment by jchodera** [comment]
Hooray!

**Comment by andrrizzi** [comment]
Tests are passing now with the new `openmmtools` release.

**Pull request merged**
