### PR TITLE
Cut the 0.19.4 Release

### PR DESCRIPTION
**Pull request by Lnaden**

### CODE REVIEW

**Comment by Lnaden** [comment]
This just has the MPI parallel molecule fix and the LEaP Cerberus fix, anything else you want to add, @andrrizzi ?

**Comment by andrrizzi** [comment]
Nope, go ahead!

**Comment by andrrizzi** [comment]
Whoops! Correction, I still have a last-minute bugfix to push. Should I do it in this PR?

**Comment by Lnaden** [comment]
Yeah, there is still time, go ahead and do it in this PR, but make sure you update the release history doc

**Comment by Lnaden** [comment]
@andrrizzi looks like one of your changes messed up a dict pickle cycle restore check:
https://travis-ci.org/choderalab/yank/jobs/314856289#L2871-L2881

**Comment by andrrizzi** [comment]
This should fix it! It was a problem with comparing nested dictionaries in the new test.

**Pull request merged**
